# Generated by Django 5.0.6 on 2024-05-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
