# Generated by Django 5.0.6 on 2024-05-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_telegrammessage_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='chat_id',
        ),
    ]
