# Generated by Django 5.0.6 on 2024-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_telegrammessage_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrammessage',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='message',
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
