# Generated by Django 5.0.6 on 2024-05-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_name_telegrammessage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='image',
            field=models.ImageField(null=True, upload_to='products', verbose_name='фото'),
        ),
    ]
