# Generated by Django 5.0.6 on 2024-05-21 00:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_telegrammessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
