# Generated by Django 5.0.6 on 2024-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_telegrammessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='title',
            field=models.CharField(max_length=455),
        ),
    ]
