# Generated by Django 5.0.6 on 2024-05-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_telegrammessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
