# Generated by Django 5.0.6 on 2024-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_telegrammessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
