# Generated by Django 5.0.6 on 2024-05-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_telegrammessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='image',
        ),
    ]
