# Generated by Django 5.0.6 on 2024-05-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_telegrammessage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'verbose_name': 'Телеграм оповещение', 'verbose_name_plural': 'Телеграм оповещения'},
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='image',
            field=models.URLField(default=1, verbose_name='Фото URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='price',
            field=models.FloatField(default=None, null=True, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='title',
            field=models.CharField(max_length=455, verbose_name='Название продукта'),
        ),
    ]
