# Generated by Django 5.0.6 on 2024-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия варианта')),
                ('category', models.ManyToManyField(to='product.category')),
            ],
            options={
                'verbose_name': 'Названия варианта',
                'verbose_name_plural': 'Названия варианта',
            },
        ),
    ]
