# Generated by Django 5.0.6 on 2024-05-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_sell_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='Продукт'),
        ),
    ]
