# Generated by Django 5.0.6 on 2024-05-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_variantvalue_price_variantvalue_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantvalue',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variantvalue',
            name='product',
        ),
        migrations.AlterField(
            model_name='variantvalue',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Варианты'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='Продукт')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Варианты')),
                ('variant_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variantvalue', verbose_name='Значение варианты')),
            ],
            options={
                'verbose_name': 'Вариант продукта',
                'verbose_name_plural': 'Варианты продукты',
            },
        ),
    ]
