# Generated by Django 5.0.6 on 2024-05-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_variantvalue_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=None, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Варианты'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variantvalue', verbose_name='Значение варианты'),
        ),
    ]
