# Generated by Django 5.0.6 on 2024-05-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productvariant_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=None, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='product.product', verbose_name='Продукт')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variant', verbose_name='Варианты')),
                ('variant_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variantvalue', verbose_name='Значение варианты')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
    ]
