# Generated by Django 5.0.6 on 2024-05-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_variantcombination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant',
            new_name='variant_name',
        ),
    ]
