# Generated by Django 5.0.6 on 2024-05-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_variant_productvariant_variant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantcombination',
            old_name='variant',
            new_name='variant_name',
        ),
    ]
